import { createConfig, http } from "wagmi";
import { base, foundry } from "wagmi/chains";
import { injected } from "wagmi/connectors";

import addresses from "../contracts/addresses.json";

/// Chain the dashboard talks to. Local anvil for the demo; Base for anything
/// real. `addresses.json` is regenerated by contracts/script/Deploy.s.sol, so
/// redeploying never means editing the frontend.
export const chain = addresses.chainId === base.id ? base : foundry;

export const wagmiConfig = createConfig({
  chains: [chain],
  connectors: [injected()],
  transports: {
    [foundry.id]: http("http://localhost:8545"),
    [base.id]: http(),
  },
});

export const contracts = {
  usdc: addresses.usdc as `0x${string}`,
  pool: addresses.pool as `0x${string}`,
  oracle: addresses.oracle as `0x${string}`,
  policyManager: addresses.policyManager as `0x${string}`,
};

/// USDC and our MockUSDC both use 6 decimals.
export const USDC_DECIMALS = 6;
