// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {PayoutMath} from "../src/PayoutMath.sol";

/// @dev PayoutMath is a library, so its functions inline into the caller and a
///      revert happens at the same call depth as the cheatcode. `expectRevert`
///      needs a real external boundary, which this harness provides.
contract PayoutMathHarness {
    function payoutFractionBps(uint32 trigger, uint32 exitMm, uint32 observed)
        external
        pure
        returns (uint256)
    {
        return PayoutMath.payoutFractionBps(trigger, exitMm, observed);
    }
}

/// @notice Checks the Solidity payout math against the Python reference.
/// @dev `vectors.json` is generated by `pricing/tests/test_payout.py`. If the
///      two implementations ever disagree this suite fails, which is the whole
///      reason the file exists.
contract PayoutMathTest is Test {
    using stdJson for string;

    struct Vector {
        uint32 triggerMmX100;
        uint32 exitMmX100;
        uint32 observedMmX100;
        uint16 weightBps;
        uint256 sumInsuredUnits;
        uint256 expectedPayoutUnits;
    }

    function test_MatchesPythonReferenceVectors() public view {
        string memory raw = vm.readFile("test/vectors.json");
        // The generator emits `count` explicitly; forge-std has no way to read
        // an array's length from JSON.
        uint256 count = raw.readUint(".count");
        assertGt(count, 0, "no vectors found");

        for (uint256 i = 0; i < count; ++i) {
            string memory base = string.concat(".payout_cases[", vm.toString(i), "]");
            Vector memory vec = Vector({
                triggerMmX100: uint32(raw.readUint(string.concat(base, ".trigger_mm_x100"))),
                exitMmX100: uint32(raw.readUint(string.concat(base, ".exit_mm_x100"))),
                observedMmX100: uint32(raw.readUint(string.concat(base, ".observed_mm_x100"))),
                weightBps: uint16(raw.readUint(string.concat(base, ".weight_bps"))),
                sumInsuredUnits: raw.readUint(string.concat(base, ".sum_insured_units")),
                expectedPayoutUnits: raw.readUint(string.concat(base, ".expected_payout_units"))
            });

            uint256 actual = PayoutMath.phasePayout(
                vec.sumInsuredUnits,
                vec.weightBps,
                vec.triggerMmX100,
                vec.exitMmX100,
                vec.observedMmX100
            );

            assertEq(
                actual,
                vec.expectedPayoutUnits,
                string.concat("vector ", vm.toString(i), " diverges from Python reference")
            );
        }
    }

    // ------------------------------------------------------------ boundaries

    function test_NoPayoutAtTrigger() public pure {
        assertEq(PayoutMath.payoutFractionBps(16_600, 14_600, 16_600), 0);
    }

    function test_NoPayoutAboveTrigger() public pure {
        assertEq(PayoutMath.payoutFractionBps(16_600, 14_600, 40_000), 0);
    }

    function test_FullPayoutAtExit() public pure {
        assertEq(PayoutMath.payoutFractionBps(16_600, 14_600, 14_600), 10_000);
    }

    function test_FullPayoutBelowExit() public pure {
        assertEq(PayoutMath.payoutFractionBps(16_600, 14_600, 0), 10_000);
    }

    function test_LinearMidpoint() public pure {
        // midway between 146.00mm and 166.00mm is 156.00mm
        assertEq(PayoutMath.payoutFractionBps(16_600, 14_600, 15_600), 5_000);
    }

    function test_RevertsWhenExitNotBelowTrigger() public {
        PayoutMathHarness harness = new PayoutMathHarness();
        vm.expectRevert(
            abi.encodeWithSelector(PayoutMath.ExitNotBelowTrigger.selector, uint32(100), uint32(100))
        );
        harness.payoutFractionBps(100, 100, 50);
    }

    function test_RevertsWhenExitAboveTrigger() public {
        PayoutMathHarness harness = new PayoutMathHarness();
        vm.expectRevert(
            abi.encodeWithSelector(PayoutMath.ExitNotBelowTrigger.selector, uint32(100), uint32(150))
        );
        harness.payoutFractionBps(100, 150, 50);
    }

    function test_WeightScalesPayout() public pure {
        // 55% weight, total failure -> 55% of sum insured
        uint256 payout = PayoutMath.phasePayout(1_000_000, 5_500, 16_600, 14_600, 0);
        assertEq(payout, 550_000);
    }

    // ----------------------------------------------------------------- fuzz

    function testFuzz_FractionNeverExceedsBps(uint32 trigger, uint32 exitMm, uint32 observed)
        public
        pure
    {
        vm.assume(trigger > 0);
        vm.assume(exitMm < trigger);
        assertLe(PayoutMath.payoutFractionBps(trigger, exitMm, observed), 10_000);
    }

    function testFuzz_PayoutNeverExceedsWeightedExposure(
        uint128 sumInsured,
        uint16 weightBps,
        uint32 trigger,
        uint32 exitMm,
        uint32 observed
    ) public pure {
        vm.assume(trigger > 0);
        vm.assume(exitMm < trigger);
        vm.assume(weightBps <= 10_000);

        uint256 payout =
            PayoutMath.phasePayout(sumInsured, weightBps, trigger, exitMm, observed);
        uint256 maxExposure = (uint256(sumInsured) * weightBps) / 10_000;
        assertLe(payout, maxExposure);
    }

    function testFuzz_MonotonicInObserved(uint32 trigger, uint32 exitMm, uint32 a, uint32 b)
        public
        pure
    {
        vm.assume(trigger > 0);
        vm.assume(exitMm < trigger);
        vm.assume(a < b);
        // More rain never means a larger payout.
        assertGe(
            PayoutMath.payoutFractionBps(trigger, exitMm, a),
            PayoutMath.payoutFractionBps(trigger, exitMm, b)
        );
    }
}
