#!/usr/bin/env bash
# Export contract ABIs into the dashboard as typed TS constants.
#
# Run after any contract change:
#   ./script/export-abis.sh
#
# `as const` matters: wagmi derives argument and return types from the literal
# ABI, so without it every read comes back untyped.

set -euo pipefail

cd "$(dirname "$0")/.."
OUT="../dashboards/src/contracts"
mkdir -p "$OUT"

forge build >/dev/null

for name in Pool PolicyManager RainfallOracle; do
  {
    echo "// Generated by contracts/script/export-abis.sh — do not edit."
    echo "export const ${name,}Abi = $(forge inspect "$name" abi --json) as const;"
  } > "$OUT/${name,}Abi.ts"
  echo "wrote $OUT/${name,}Abi.ts"
done

# MockUSDC stands in for USDC locally; the real thing has the same interface.
{
  echo "// Generated by contracts/script/export-abis.sh — do not edit."
  echo "export const erc20Abi = $(forge inspect MockUSDC abi --json) as const;"
} > "$OUT/erc20Abi.ts"
echo "wrote $OUT/erc20Abi.ts"
